export type Token = {
  address: string;
  logo_uri: string;
  name: string;
  symbol: string;
  decimals: number;
  extensions: any; 
  market_cap: number;
  fdv: number;
  liquidity: number;
  last_trade_unix_time: number;
  volume_1h_usd: number;
  volume_1h_change_percent: number;
  volume_2h_usd: number;
  volume_2h_change_percent: number;
  volume_4h_usd: number;
  volume_4h_change_percent: number;
  volume_8h_usd: number;
  volume_8h_change_percent: number;
  volume_24h_usd: number;
  volume_24h_change_percent: number | null;
  trade_1h_count: number;
  trade_2h_count: number;
  trade_4h_count: number;
  trade_8h_count: number;
  trade_24h_count: number;
  price: number;
  price_change_1h_percent: number;
  price_change_2h_percent: number;
  price_change_4h_percent: number;
  price_change_8h_percent: number;
  price_change_24h_percent: number | null;
  holder: number;
  recent_listing_time: number;
};
