import type { Metadata } from "next";
import LocalFont from "next/font/local";

import "./globals.css";


const aiWriterDouspace = LocalFont({
  src: [
    {
      weight: "500",
      path: "./assets/fonts/iAWriterDuospace-Regular.ttf",
    },
    {
      weight: "700",
      path: "./assets/fonts/iAWriterDuospace-Bold.ttf",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={aiWriterDouspace.className}>{children}</body>
    </html>
  );
}
